// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzspdq1Lq7Jq_8pBAaL9rWdG-br0w_3I',
    appId: '1:163385379419:web:545dfdf4708b7bded6cd7e',
    messagingSenderId: '163385379419',
    projectId: 'finkia',
    authDomain: 'finkia.firebaseapp.com',
    storageBucket: 'finkia.firebasestorage.app',
    measurementId: 'G-50L183688X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcCmYmUGvIu5mgC5lvRaX9_JXzu-x2WMo',
    appId: '1:163385379419:android:d24e643354f4b6b7d6cd7e',
    messagingSenderId: '163385379419',
    projectId: 'finkia',
    storageBucket: 'finkia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD42Y7LjwPwvb6kUDivabeb-0-ke4sRG0M',
    appId: '1:163385379419:ios:71d70b10e8db61c8d6cd7e',
    messagingSenderId: '163385379419',
    projectId: 'finkia',
    storageBucket: 'finkia.firebasestorage.app',
    iosBundleId: 'com.example.agrouAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD42Y7LjwPwvb6kUDivabeb-0-ke4sRG0M',
    appId: '1:163385379419:ios:71d70b10e8db61c8d6cd7e',
    messagingSenderId: '163385379419',
    projectId: 'finkia',
    storageBucket: 'finkia.firebasestorage.app',
    iosBundleId: 'com.example.agrouAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzspdq1Lq7Jq_8pBAaL9rWdG-br0w_3I',
    appId: '1:163385379419:web:31a40cad8d5bafb0d6cd7e',
    messagingSenderId: '163385379419',
    projectId: 'finkia',
    authDomain: 'finkia.firebaseapp.com',
    storageBucket: 'finkia.firebasestorage.app',
    measurementId: 'G-DW23RG86SB',
  );
}
